/*
 * Copyright (c) 2014. Copyright (c) 2014. Matthew Campbell <matthew.campbell@mq.edu.au>
 *
 * The program can not be distributed to others with out the consent of the copyright holder, until such a time that the copyright holder has released the code for public use.
 */

package models.unicarbdb.core;

import models.unicarbdb.hplc.Lcmucin;

import javax.persistence.*;
import java.util.Date;
import java.util.List;



@Entity
@Table(schema="core", name="biological_context")
public class BiologicalContext  {
	
	/** Canonical id */

	//public int biologicalContextId;
	 @Id
	 @Column(name="biological_context_id")
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "biological_gen")
     @SequenceGenerator(name = "biological_gen", sequenceName = "core.biological_context_biological_context_id_seq", allocationSize=1)
    public Long biological_context_id; //Id;

    /**
     * Date this context was entered into the data store - this value is
     * auto-generated by the database!
     */
    public Date dateEntered = new Date();

    /** The taxonomy comprising this context. */
    @ManyToOne
    @JoinColumn(name="taxonomy_id")
    public Taxonomy taxonomy;

    /** The tissue taxonomy comprising this context. */
    @ManyToOne
    @JoinColumn(name="tissue_taxonomy_id")
    public TissueTaxonomy tissueTaxonomy;

    /** The {@link Contributor} of this context. */
    protected Contributor contributor;
    
    //@OneToMany
    //public List<Lcmucin> lcmucin;

    @OneToMany(mappedBy = "biologicalContext")
    public List<models.unicarbdb.hplc.Lcmucin> lcmucin; // = new HashSet<Lcmucin>(0);

    public Long getBiological_context_id() {
        return biological_context_id;
    }

    public void setBiological_context_id(Long biological_context_id) {
        this.biological_context_id = biological_context_id;
    }

    public Date getDateEntered() {
        return dateEntered;
    }

    public void setDateEntered(Date dateEntered) {
        this.dateEntered = dateEntered;
    }

    public Taxonomy getTaxonomy() {
        return taxonomy;
    }

    public void setTaxonomy(Taxonomy taxonomy) {
        this.taxonomy = taxonomy;
    }

    public TissueTaxonomy getTissueTaxonomy() {
        return tissueTaxonomy;
    }

    public void setTissueTaxonomy(TissueTaxonomy tissueTaxonomy) {
        this.tissueTaxonomy = tissueTaxonomy;
    }

    public Contributor getContributor() {
        return contributor;
    }

    public void setContributor(Contributor contributor) {
        this.contributor = contributor;
    }

    public List<Lcmucin> getLcmucin() {
        return lcmucin;
    }

    public void setLcmucin(List<Lcmucin> lcmucin) {
        this.lcmucin = lcmucin;
    }
}
